name: Build and Lint Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  packages: read
  id-token: write

env:
  SKIP_ENV_VALIDATION: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [self-hosted] # Possible values: [ubuntu-latest, windows-latest, macOS-latest, self-hosted]
        test: [lint, tsc]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable corepack
        run: corepack enable

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build and Run ${{ matrix.test }}
        run: |
          pnpm ${{ matrix.test }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
